version: '3'

services:
  frontend:
    build:
      context: ./FrontEnd/my-app
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ./FrontEnd/my-app

  backend:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ./UserService

  resultservice:
    build:
      context: ./ResultService
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ./ResultService