name: CI/CD Pipeline user service

on:
  push:
    branches:
      - topias

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        cd UserService/
        npm ci

    - name: Build and test
      run: |
        cd UserService/
        screen -dmS node-server node .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker metadata
      uses: docker/metadata-action@v3
      with:
        images: 'userservicecontainer'

    - name: Build Docker image
      run: |
        cd UserService/
        docker build -t userservice .

    - name: Push Docker image
      run: |
        cd UserService/
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push tuupsuu/userservicecontainer


    - name: Deploy to Docker server
      run: |
        cd UserService/
        ssh 172.104.236.131 'docker pull tuupsuu/userservicecontainer'
        ssh 172.104.236.131 'docker stop userservice || true'
        ssh 172.104.236.131 'docker rm userservice || true'
        ssh 172.104.236.131 'docker run -d --name userservice -p 80:80 tuupsuu/userservicecontainer'
